# Generated by Django 5.2.6 on 2026-10-01 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, verbose_name='identificador')),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('OCCUPIED', 'Ocupada')], default='FREE', max_length=20, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='locations.venue', verbose_name='sede')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['venue__name', 'identifier'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'identifier'), name='unique_table_identifier_per_venue')],
            },
        ),
    ]
