# Generated by Django 5.2.6 on 2026-10-01 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_supplier'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada de mercancía')], max_length=20, verbose_name='tipo de movimiento')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha y hora')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product', verbose_name='producto')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='locations.venue', verbose_name='sede')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad disponible')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.product', verbose_name='producto')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='locations.venue', verbose_name='sede')),
            ],
            options={
                'verbose_name': 'existencia',
                'verbose_name_plural': 'existencias',
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'product'), name='unique_stock_per_venue_product')],
            },
        ),
    ]
