# Generated by Django 5.2.6 on 2026-10-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='orders.order', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entrada de mercancía'), ('ORDER_DISCOUNT', 'Descuento por pedido'), ('ORDER_RESTORE', 'Reintegro por cancelación de pedido')], max_length=20, verbose_name='tipo de movimiento'),
        ),
    ]
