# Generated by Django 5.2.6 on 2026-10-01 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_CASHIER', 'En caja')], default='OPEN', max_length=20, verbose_name='estado')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora de apertura')),
                ('sent_to_cashier_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora de envío a caja')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.table', verbose_name='mesa')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='locations.venue', verbose_name='sede')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='mesero')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('table',), name='unique_open_order_per_table')],
            },
        ),
    ]
