# Generated by Django 5.2.6 on 2026-09-17 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='nombre de usuario')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Intento de inicio de sesión fallido'), ('LOGIN_BLOCKED', 'Acceso bloqueado por intentos fallidos')], max_length=40, verbose_name='tipo de evento')),
                ('entity', models.CharField(blank=True, max_length=60, verbose_name='entidad afectada')),
                ('entity_id', models.CharField(blank=True, max_length=40, verbose_name='id de la entidad')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'eventos de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='audit_audit_event_t_124af2_idx'), models.Index(fields=['username'], name='audit_audit_usernam_398662_idx')],
            },
        ),
    ]
