# Generated by Django 5.2.6 on 2026-09-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Intento de inicio de sesión fallido'), ('LOGIN_BLOCKED', 'Acceso bloqueado por intentos fallidos'), ('SESSION_TIMEOUT', 'Cierre de sesión por inactividad')], max_length=40, verbose_name='tipo de evento'),
        ),
    ]
