# Generated by Django 5.2.6 on 2026-09-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Intento de inicio de sesión fallido'), ('LOGIN_BLOCKED', 'Acceso bloqueado por intentos fallidos'), ('SESSION_TIMEOUT', 'Cierre de sesión por inactividad'), ('SESSION_LOGOUT', 'Cierre de sesión manual'), ('SESSION_DISCONNECTED', 'Cierre de sesión por pérdida de conexión'), ('VENUE_CREATED', 'Creación de sede')], max_length=40, verbose_name='tipo de evento'),
        ),
    ]
