# Generated by Django 5.2.6 on 2026-10-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Intento de inicio de sesión fallido'), ('LOGIN_BLOCKED', 'Acceso bloqueado por intentos fallidos'), ('SESSION_TIMEOUT', 'Cierre de sesión por inactividad'), ('SESSION_LOGOUT', 'Cierre de sesión manual'), ('SESSION_DISCONNECTED', 'Cierre de sesión por pérdida de conexión'), ('SESSION_REVOKED', 'Sesión revocada por el sistema'), ('VENUE_CREATED', 'Creación de sede'), ('VENUE_UPDATED', 'Modificación de sede'), ('VENUE_DEACTIVATED', 'Inactivación de sede'), ('USER_CREATED', 'Creación de usuario'), ('USER_UPDATED', 'Modificación de usuario'), ('USER_DEACTIVATED', 'Inactivación de usuario'), ('USER_REACTIVATED', 'Reactivación de usuario'), ('PRODUCT_CREATED', 'Creación de producto'), ('PRODUCT_UPDATED', 'Modificación de producto')], max_length=40, verbose_name='tipo de evento'),
        ),
    ]
