# Generated by Django 5.2.6 on 2026-09-17 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='nombre de usuario')),
                ('successful', models.BooleanField(default=False, verbose_name='exitoso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha y hora')),
            ],
            options={
                'verbose_name': 'intento de inicio de sesión',
                'verbose_name_plural': 'intentos de inicio de sesión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='rol')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora de ingreso')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='última actividad')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora de cierre')),
                ('closing_reason', models.CharField(choices=[('ACTIVE', 'Sesión activa')], default='ACTIVE', max_length=20, verbose_name='motivo de cierre')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'sesión de usuario',
                'verbose_name_plural': 'sesiones de usuario',
                'ordering': ['-started_at'],
            },
        ),
    ]
