# Generated by Django 5.2.6 on 2026-09-17 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usersession_closing_reason'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='locations.venue', verbose_name='sede'),
        ),
    ]
