# Generated by Django 5.2.6 on 2026-09-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usersession_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='closing_reason',
            field=models.CharField(choices=[('ACTIVE', 'Sesión activa'), ('INACTIVITY', 'Cierre automático por inactividad'), ('MANUAL', 'Cierre manual por el usuario'), ('DISCONNECTION', 'Cierre por pérdida de conexión'), ('USER_DEACTIVATED', 'Cierre por inactivación de la cuenta')], default='ACTIVE', max_length=20, verbose_name='motivo de cierre'),
        ),
    ]
