# Generated by Django 5.2.6 on 2026-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Debe ser único en el catálogo.', max_length=150, unique=True, verbose_name='nombre')),
                ('product_type', models.CharField(max_length=80, verbose_name='tipo')),
                ('category', models.CharField(max_length=80, verbose_name='categoría')),
                ('purchase_price', models.PositiveIntegerField(verbose_name='valor de compra')),
                ('sale_price', models.PositiveIntegerField(verbose_name='valor de venta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['product_type'], name='catalog_pro_product_9ecdd3_idx'), models.Index(fields=['category'], name='catalog_pro_categor_50f92a_idx')],
            },
        ),
    ]
