# Generated by Django 5.2.6 on 2026-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Debe ser único en el directorio de proveedores.', max_length=150, unique=True, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['name'],
            },
        ),
    ]
