# Generated by Django 5.2.6 on 2026-09-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='No pueden existir dos sedes con el mismo nombre.', max_length=120, unique=True, verbose_name='nombre')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedes',
                'ordering': ['name'],
            },
        ),
    ]
